name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - 'client/**'
      - 'query/**'
      - 'comments/**'
      - 'event-bus/**'
      - 'moderation/**'
      - 'posts/**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      # Install dependencies based on folder changes
      - name: Install dependencies for Orders
        if: contains(github.event.head_commit.message, 'query/')
        run: cd orders && npm install
      
      - name: Install dependencies for Client
        if: contains(github.event.head_commit.message, 'client/')
        run: cd client && npm install

      - name: Install dependencies for Comments
        if: contains(github.event.head_commit.message, 'comments/')
        run: cd comments && npm install

      - name: Install dependencies for Eventbus
        if: contains(github.event.head_commit.message, 'event-bus/')
        run: cd eventbus && npm install

      - name: Install dependencies for Moderation
        if: contains(github.event.head_commit.message, 'moderation/')
        run: cd moderation && npm install

      - name: Install dependencies for Posts
        if: contains(github.event.head_commit.message, 'posts/')
        run: cd posts && npm install
      

  